### ISSUE TITLE
Thinking of adding game pads to this logic

### ISSUE THREAD

**Issue by terrac** [fenomas/game-inputs#4]
Seems like it would be easy and a nice thing to have.

**Comment by andyhall** [comment]
Hey, this would be great!

If possible, I guess stick to the current API - so buttons would map to vkey-style codes (`<gamepad 1>` or whatever?), and axes would be handled like mouse input. Maybe `state.axes[0].dx / dy`?

But I haven't looked at it carefully, maybe something else makes more sense.
