### ISSUE TITLE
Plans for full touch support?

### ISSUE THREAD

**Issue by MCArth** [fenomas/game-inputs#6]
I'm having some performance issues with my touch implementation - before I put too much time into it, I'm wondering if you have plans to implement full touch support here and in noa in the short term and/or long term?

**Comment by fenomas** [comment]
Hi, the short answer is that I'd like this lib and noa to both "support" touch, in the sense that they provide all the APIs/etc for a touch-based game client, and that all those APIs work correctly etc. But I'm not actively developing or testing on any touch devices.

So, no plans, happy to receive issues/PRs/etc.

**Comment by MCArth** [comment]
Ok! Would a joystick be within the remit of this library? I'm using an external library at the moment, but it doesn't make the most use of CPU time.

I'll let you know if and when I do something, it's a substantial piece of work

**Comment by fenomas** [comment]
Oh, absolutely on the joystick. I wasn't sure if it was into caniuse territory. But one wants to get all such events through the same library, so would be very good for this one. I'll add a tracking issue, if you wind up doing anything with it!
